GET http://127.0.0.1:3000/user HTTP/1.1

###

GET http://127.0.0.1:3000/user/francis.gagne+test-keycloak@sct.gouv.qc.ca HTTP/1.1

###
POST http://127.0.0.1:3000/user HTTP/1.1
content-type: application/json

{
    "email": "francis.gagne+test-keycloak@sct.gouv.qc.ca",
    "firstname": "Frank",
    "lastname": "The Test",
    "organisation": "CQEN",
    "infrarole": "Developer"
}

###

PUT http://127.0.0.1:3000/user/francis.gagne+test-keycloak@sct.gouv.qc.ca HTTP/1.1
content-type: application/json

{
    "firstname": "Francis",
    "lastname": "Le Test",
    "organisation": "CQEN",
    "infrarole": "Developer"
}