GET http://127.0.0.1:3000/user HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/user/test@example.com HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
POST http://127.0.0.1:3000/user HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "email": "bobby@example.com",
    "firstname": "Bobby",
    "lastname": "Example",
    "organisation": "CQEN",
    "infrarole": "Developer"
}

###
PUT http://127.0.0.1:3000/user/bobby@example.com HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "firstname": "Bobby",
    "lastname": "Test",
    "organisation": "ORGP"
}

###
DELETE http://127.0.0.1:3000/user/test@example.com HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/laboratory HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/laboratory/dev1 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
POST http://127.0.0.1:3000/laboratory HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "id": "dev2",
    "type": "experimentation",
    "displayname":"Lab dev2 test",
    "description":"Description de Lab dev2 test",
    "gitrepo":"https://github.com/CQEN-QDCE/ceai-cqen-admin-api"
}

###
PUT http://127.0.0.1:3000/laboratory/dev2 HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "type": "experimentation",
    "displayname":"Lab dev2 test",
    "description":"Description de Lab dev2 test",
    "gitrepo":"https://github.com/CQEN-QDCE/ceai-cqen-admin-api"
}

###
PUT http://127.0.0.1:3000/laboratory/dev2/user HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

["bobby@example.com"]

###
DELETE http://127.0.0.1:3000/laboratory/dev2/user HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

["test@example.com"]

### 
PUT http://127.0.0.1:3000/laboratory/dev2/openshift/dev1-project1 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

### 
DELETE http://127.0.0.1:3000/laboratory/dev2/openshift/dev1-project1 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/openshift/project HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/openshift/project/dev1-project1 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
POST http://127.0.0.1:3000/openshift/project HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "id": "dev2-project-1",
    "displayname": "Dev2 app 1",
    "description": "Application 1 du laboratoire dev2",
    "idLab": "dev2"
}

###
PUT http://127.0.0.1:3000/openshift/project/dev2-project-1 HTTP/1.1
content-type: application/json
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

{
    "displayname": "Dev2 app 1",
    "description": "Application 1 du laboratoire dev2",
    "idLab": "dev2"
}

###
GET http://127.0.0.1:3000/aws/account HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
GET http://127.0.0.1:3000/aws/account/111111111111 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
PUT http://127.0.0.1:3000/laboratory/dev2/aws/111111111111 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin

###
DELETE http://127.0.0.1:3000/laboratory/dev2/aws/111111111111 HTTP/1.1
X-CEAI-Username: test@example.com
X-CEAI-UserRoles : Admin