- id: Identifiant1
  displayname: Nom complet du project 1
  description: Description 1
  idLab: IdLab1
- id: Identifiant2
  displayname: Nom complet du project 2
  description: Description 2
  idLab: IdLab1