kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ceai-admin-api-admin
subjects:
  - kind: ServiceAccount
    name: ceai-admin-api
    namespace: openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin